version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pasamos las variables del archivo .env al Dockerfile durante la construcción
        - VITE_EMAILJS_SERVICE_ID=${VITE_EMAILJS_SERVICE_ID}
        - VITE_EMAILJS_TEMPLATE_ID=${VITE_EMAILJS_TEMPLATE_ID}
        - VITE_EMAILJS_PUBLIC_KEY=${VITE_EMAILJS_PUBLIC_KEY}
    image: landing-page-sse:latest
    container_name: landing-page-sse
    restart: unless-stopped
    ports:
      # Mapeamos el puerto 80 del contenedor al puerto 8080 del VPS
      # Usamos 8080 para no chocar con el Nginx principal del VPS
      - "127.0.0.1:8080:80"