services:
  web:
    image: landing-page-sse:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
        VITE_EMAILJS_TEMPLATE_ID: ${VITE_EMAILJS_TEMPLATE_ID}
        VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
    ports:
      - "80:80"
    restart: unless-stopped
